// eslint-disable-next-line import/prefer-default-export
export const constants = {
  MONTH_RU: [
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь",
  ],
  MONTH_REF: [
    "jan",
    "feb",
    "mar",
    "apr",
    "may",
    "june",
    "july",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
  ],
  YEAR_MONTH_ROUTE: /year\/\d+\/month\/\w+/,
  YEAR_ROUTE: /year\/(\d+)/,
  MONTH_ROUTE: /month\/(\w+)/,
};
