name: Test

on: pull_request

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm test